trigger:
- main

pool:
  name: 'SelfHostedAgentPools'

steps:
- task: AzureCLI@2
  displayName: 'Crear cuenta de almacenamiento'
  inputs:
    azureSubscription: 'AzureResourceManager'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az storage account create --name appiumtestreport --resource-group GR-QA --location eastus --sku Standard_LRS

- task: AzureCLI@2
  displayName: 'Obtener clave de acceso a la cuenta de almacenamiento'
  inputs:
    azureSubscription: 'AzureResourceManager'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      $storageAccountKey = az storage account keys list --resource-group GR-QA --account-name appiumtestreport --query '[0].value' --output tsv
      echo "##vso[task.setvariable variable=StorageAccountKey]$storageAccountKey"

- task: AzureCLI@2
  displayName: 'Habilitar el sitio estático en la cuenta de almacenamiento'
  inputs:
    azureSubscription: 'AzureResourceManager'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az storage blob service-properties update --account-name appiumtestreport --static-website --404-document 404.html --index-document overview-features.html --account-key $(StorageAccountKey)