trigger:
- main

pool:
  name: 'PortafolioAG'

steps:
- task: AzureCLI@2
  displayName: 'Crear cuenta de almacenamiento'
  inputs:
    azureSubscription: 'AzureResourceManager'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az storage account create --name cucumbertestreport01 --resource-group GR-QA --location eastus --sku Standard_LRS

- task: AzureCLI@2
  displayName: 'Obtener clave de acceso a la cuenta de almacenamiento'
  inputs:
    azureSubscription: 'AzureResourceManager'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      $storageAccountKey = az storage account keys list --resource-group GR-QA --account-name cucumbertestreport01 --query '[0].value' --output tsv

- task: AzureCLI@2
  displayName: 'Habilitar acceso anónimo en la cuenta de almacenamiento'
  inputs:
    azureSubscription: 'AzureResourceManager'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az storage account update --name cucumbertestreport01 --resource-group GR-QA --allow-blob-public-access true

- task: AzureCLI@2
  displayName: 'Crear contenedor en la cuenta de almacenamiento'
  inputs:
    azureSubscription: 'AzureResourceManager'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az storage container create --name testreport --account-name cucumbertestreport01 --account-key $(StorageAccountKey) --public-access blob

- task: AzureCLI@2
  displayName: 'Habilitar el sitio estático en la cuenta de almacenamiento'
  inputs:
    azureSubscription: 'AzureResourceManager'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az storage blob service-properties update --account-name cucumbertestreport01 --static-website --404-document 404.html --index-document overview-features.html --account-key $(StorageAccountKey)