trigger:
- main

pool:
  name: 'PortafolioAG'

steps:
- task: AzureCLI@2
  displayName: 'Azure Login'
  inputs:
    azureSubscription: 'AzureResourceManager'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: 'az login --identity'

- task: AzureCLI@2
  displayName: 'Crear cuenta de almacenamiento'
  inputs:
    azureSubscription: 'AzureResourceManager'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az storage account create --name TestReport --resource-group GR-QA --location eastus --sku Standard_LRS

- task: AzureCLI@2
  displayName: 'Obtener clave de acceso a la cuenta de almacenamiento'
  inputs:
    azureSubscription: 'AzureResourceManager'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      storageAccountKey=$(az storage account keys list --resource-group GR-QA --account-name TestReport --query '[0].value' --output tsv)

- task: AzureCLI@2
  displayName: 'Crear contenedor en la cuenta de almacenamiento'
  inputs:
    azureSubscription: 'AzureResourceManager'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az storage container create --name AppiumCucumberReport --account-name TestReport --account-key $storageAccountKey
