trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: AzureCLI@2
  displayName: 'Crear cuenta de almacenamiento'
  inputs:
    azureSubscription: 'AzureResourceManager'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az storage account create --name storageab --resource-group rg-ab-001 --location eastus --sku Standard_LRS

- task: AzureCLI@2
  displayName: 'Obtener clave de acceso a la cuenta de almacenamiento'
  inputs:
    azureSubscription: 'AzureResourceManager'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      $storageAccountKey = az storage account keys list --resource-group rg-ab-001 --account-name storageab --query '[0].value' --output tsv
      echo "##vso[task.setvariable variable=StorageAccountKey]$storageAccountKey"

- task: AzureCLI@2
  displayName: 'Habilitar el sitio estático en la cuenta de almacenamiento'
  inputs:
    azureSubscription: 'AzureResourceManager'
    scriptType: 'ps'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az storage blob service-properties update --account-name storageab --static-website --404-document 404.html --index-document overview-features.html --account-key $(StorageAccountKey)